version: "3"

services:
  database:
    container_name: cp-db
    image: postgres:alpine
    environment:
      - POSTGRES_DB=chatplatform-dev
      - POSTGRES_USER=chatplatform
      - POSTGRES_PASSWORD=chatplatform
    ports:
      - "3000:5432"

  backend:
    container_name: cp-backend
    depends_on: 
      - database
    build:
      context: ../chat-platform-full-stack-training
      dockerfile: Dockerfile
    volumes:
    - "../chat-platform-full-stack-training:/usr/src/app"
    - "/usr/src/app/node_modules"
    environment:
      - PORT=3000
      - DB_DEV=chatplatform-dev
      - DB_USER=chatplatform
      - DB_PASSWORD=chatplatform
      - DB_ADDR=database
      - DB_PORT=5432
    ports:
      - "3001:3000"
    command: sh -c " sh migrate.sh && npm run dev "
    
  frontend:
    container_name: cp-frontend
    build:
      context: ../chat-platform-full-stack-training-frontend
      dockerfile: Dockerfile
    volumes:
    - "../chat-platform-full-stack-training-frontend:/usr/src/app"
    - "/usr/src/app/node_modules"
    environment:
      - REACT_APP_BACKEND_ADDR=localhost
      - REACT_APP_BACKEND_PORT=3001
    ports:
      - "3002:3000"
